// Metadata
export const SITE_NAME = "ClinicalTrials.gov API"
export const SITE_DESCRIPTION =
  "Explore the ClinicalTrials.gov API with a simple interface"
export const CLINICAL_TRIALS_API_ABOUT_URL =
  "https://clinicaltrials.gov/data-api/about-api"
export const CLINICAL_TRIALS_API_BASE_URL = "https://clinicaltrials.gov/api/v2"
export const CLINICAL_TRIALS_API_MAXIMUM_PAGE_SIZE = 1000

export const CLINICAL_TRIALS_API_ENUMS = {
  OrgStudyIdType: ["NIH", "FDA", "VA", "CDC", "AHRQ", "SAMHSA"],
  SecondaryIdType: [
    "NIH",
    "FDA",
    "VA",
    "CDC",
    "AHRQ",
    "SAMHSA",
    "OTHER_GRANT",
    "EUDRACT_NUMBER",
    "CTIS",
    "REGISTRY",
    "OTHER",
  ],
  AgencyClass: [
    "NIH",
    "FED",
    "OTHER_GOV",
    "INDIV",
    "INDUSTRY",
    "NETWORK",
    "AMBIG",
    "OTHER",
    "UNKNOWN",
  ],
  Status: [
    "ACTIVE_NOT_RECRUITING",
    "COMPLETED",
    "ENROLLING_BY_INVITATION",
    "NOT_YET_RECRUITING",
    "RECRUITING",
    "SUSPENDED",
    "TERMINATED",
    "WITHDRAWN",
    "AVAILABLE",
    "NO_LONGER_AVAILABLE",
    "TEMPORARILY_NOT_AVAILABLE",
    "APPROVED_FOR_MARKETING",
    "WITHHELD",
    "UNKNOWN",
  ],
  ExpandedAccessStatus: [
    "AVAILABLE",
    "NO_LONGER_AVAILABLE",
    "TEMPORARILY_NOT_AVAILABLE",
    "APPROVED_FOR_MARKETING",
  ],
  DateType: ["ACTUAL", "ESTIMATED"],
  ResponsiblePartyType: [
    "SPONSOR",
    "PRINCIPAL_INVESTIGATOR",
    "SPONSOR_INVESTIGATOR",
  ],
  StudyType: ["EXPANDED_ACCESS", "INTERVENTIONAL", "OBSERVATIONAL"],
  Phase: ["NA", "EARLY_PHASE1", "PHASE1", "PHASE2", "PHASE3", "PHASE4"],
  DesignAllocation: ["RANDOMIZED", "NON_RANDOMIZED", "NA"],
  InterventionalAssignment: [
    "SINGLE_GROUP",
    "PARALLEL",
    "CROSSOVER",
    "FACTORIAL",
    "SEQUENTIAL",
  ],
  PrimaryPurpose: [
    "TREATMENT",
    "PREVENTION",
    "DIAGNOSTIC",
    "ECT",
    "SUPPORTIVE_CARE",
    "SCREENING",
    "HEALTH_SERVICES_RESEARCH",
    "BASIC_SCIENCE",
    "DEVICE_FEASIBILITY",
    "OTHER",
  ],
  ObservationalModel: [
    "COHORT",
    "CASE_CONTROL",
    "CASE_ONLY",
    "CASE_CROSSOVER",
    "ECOLOGIC_OR_COMMUNITY",
    "FAMILY_BASED",
    "DEFINED_POPULATION",
    "NATURAL_HISTORY",
    "OTHER",
  ],
  TimePerspective: ["RETROSPECTIVE", "PROSPECTIVE", "CROSS_SECTIONAL", "OTHER"],
  DesignMasking: ["NONE", "SINGLE", "DOUBLE", "TRIPLE", "QUADRUPLE"],
  WhoMasked: [
    "PARTICIPANT",
    "CARE_PROVIDER",
    "INVESTIGATOR",
    "OUTCOMES_ASSESSOR",
  ],
  BioSpecRetention: [
    "NONE_RETAINED",
    "SAMPLES_WITH_DNA",
    "SAMPLES_WITHOUT_DNA",
  ],
  EnrollmentType: ["ACTUAL", "ESTIMATED"],
  Sex: ["FEMALE", "MALE", "ALL"],
  SamplingMethod: ["PROBABILITY_SAMPLE", "NON_PROBABILITY_SAMPLE"],
  ArmGroupType: [
    "EXPERIMENTAL",
    "ACTIVE_COMPARATOR",
    "PLACEBO_COMPARATOR",
    "SHAM_COMPARATOR",
    "NO_INTERVENTION",
    "OTHER",
  ],
  InterventionType: [
    "BEHAVIORAL",
    "BIOLOGICAL",
    "COMBINATION_PRODUCT",
    "DEVICE",
    "DIAGNOSTIC_TEST",
    "DIETARY_SUPPLEMENT",
    "DRUG",
    "GENETIC",
    "PROCEDURE",
    "RADIATION",
    "OTHER",
  ],
  StandardAge: ["CHILD", "ADULT", "OLDER_ADULT"],
  ContactRole: [
    "STUDY_CHAIR",
    "STUDY_DIRECTOR",
    "PRINCIPAL_INVESTIGATOR",
    "SUB_INVESTIGATOR",
    "CONTACT",
  ],
  OfficialRole: [
    "STUDY_CHAIR",
    "STUDY_DIRECTOR",
    "PRINCIPAL_INVESTIGATOR",
    "SUB_INVESTIGATOR",
  ],
  RecruitmentStatus: [
    "ACTIVE_NOT_RECRUITING",
    "COMPLETED",
    "ENROLLING_BY_INVITATION",
    "NOT_YET_RECRUITING",
    "RECRUITING",
    "SUSPENDED",
    "TERMINATED",
    "WITHDRAWN",
    "AVAILABLE",
  ],
  ReferenceType: ["BACKGROUND", "RESULT", "DERIVED"],
  IpdSharing: ["YES", "NO", "UNDECIDED"],
  IpdSharingInfoType: ["STUDY_PROTOCOL", "SAP", "ICF", "CSR", "ANALYTIC_CODE"],
  MeasureParam: [
    "GEOMETRIC_MEAN",
    "GEOMETRIC_LEAST_SQUARES_MEAN",
    "LEAST_SQUARES_MEAN",
    "LOG_MEAN",
    "MEAN",
    "MEDIAN",
    "NUMBER",
    "COUNT_OF_PARTICIPANTS",
    "COUNT_OF_UNITS",
  ],
  MeasureDispersionType: [
    "NA",
    "STANDARD_DEVIATION",
    "STANDARD_ERROR",
    "INTER_QUARTILE_RANGE",
    "FULL_RANGE",
    "CONFIDENCE_80",
    "CONFIDENCE_90",
    "CONFIDENCE_95",
    "CONFIDENCE_975",
    "CONFIDENCE_99",
    "CONFIDENCE_OTHER",
    "GEOMETRIC_COEFFICIENT",
  ],
  OutcomeMeasureType: [
    "PRIMARY",
    "SECONDARY",
    "OTHER_PRE_SPECIFIED",
    "POST_HOC",
  ],
  ReportingStatus: ["NOT_POSTED", "POSTED"],
  AnalysisDispersionType: ["STANDARD_DEVIATION", "STANDARD_ERROR_OF_MEAN"],
  ConfidenceIntervalNumSides: ["ONE_SIDED", "TWO_SIDED"],
  NonInferiorityType: [
    "SUPERIORITY",
    "NON_INFERIORITY",
    "EQUIVALENCE",
    "OTHER",
    "NON_INFERIORITY_OR_EQUIVALENCE",
    "SUPERIORITY_OR_OTHER",
    "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY",
    "SUPERIORITY_OR_OTHER_LEGACY",
  ],
  EventAssessment: ["NON_SYSTEMATIC_ASSESSMENT", "SYSTEMATIC_ASSESSMENT"],
  AgreementRestrictionType: ["LTE60", "GT60", "OTHER"],
  UnpostedEventType: ["RESET", "RELEASE", "UNRELEASE"],
  ViolationEventType: [
    "VIOLATION_IDENTIFIED",
    "CORRECTION_CONFIRMED",
    "PENALTY_IMPOSED",
    "ISSUES_IN_LETTER_ADDRESSED_CONFIRMED",
  ],
  BrowseLeafRelevance: ["LOW", "HIGH"],
} as const
